qiniu/developer.qiniu.com

- _layouts/demo.html
- _layouts/download.html
- _src/js/docs.js
https://pm.qbox.me/issues/13482
> add add-demo  entrance for demo page

- _src/js/docs.js
- docs/v6/api/overview/up/form-upload.md
https://pm.qbox.me/issues/13831
> update js for portal 、remove demo link for form-upload 

- _layouts/homepage.html
- docs/v6/kb/testing.md
https://pm.qbox.me/issues/14175
> fix deadlink

- _data/demo.json
- _data/resource.json
https://pm.qbox.me/issues/14405
> 14405 resource update

- _data/resource.json
> add fib.js demo

- docs/v6/sdk/csharp-sdk.md
> added some style

- docs/v6/api/overview/fop/fop/index.md
- docs/v6/api/overview/fop/index.md
> link error

- docs/v6/sdk/android-sdk.md
> android-sdk 7.0.7

- docs/v6/api/reference/fop/av/avthumb.md
> retrieve directory unavailable

- docs/v6/api/overview/fop/fop/persistent-fop.md
> hyper link error

- docs/v6/api/overview/fop/fop/persistent-fop.md
- docs/v6/sdk/python-sdk.md
>  detail modify

- docs/v6/api/reference/fop/image/imageview2.md
> layout modify

- _data/resource.json
https://github.com/lenage/react-qiniu
> add react qiniu plugin

- docs/v6/api/reference/fop/image/imageview2.md
> unify directory

- docs/v6/api/overview/concepts.md
- docs/v6/api/overview/dn/security.md
- docs/v6/api/overview/dn/v2:download-settings.md
- docs/v6/api/overview/quickstart.md
- docs/v6/api/overview/up/upload-models/upload-types.md
> change qiniudn.com domain

- docs/v6/api/reference/fop/av/pm3u8.md
> feature modify

- docs/v6/api/overview/up/upload-models/response-types.md
> add debug method

- docs/v6/api/reference/rs/fetch.md
- docs/v6/tools/qrsync.md
> modify fetch and qrsync content

- docs/v6/tools/qrsbox.md
- docs/v6/tools/qrsctl.md
- docs/v6/tools/qrsync.md
- docs/v6/tools/qwebtest.md
> modify domain name

- docs/v6/api/reference/fop/pfop/pfop.md
- docs/v6/tools/qfetch.md
> unified content

- docs/v6/tools/qfetch.md
> modify download domain

- docs/v6/sdk/android-sdk.md
> modify symbol

- docs/v6/api/reference/fop/av/index.md
- docs/v6/api/reference/fop/image/index.md
- docs/v6/tools/qrsctl.md
- docs/v6/tools/qrsync.md
- docs/v6/tools/qshell.md
> add new feature and modify command

- _data/resource.json
> modify tools

- _layouts/homepage.html
- docs/v6/api/reference/fop/pfop/pfop.md
- docs/v6/api/reference/fop/pfop/prefop.md
> add new content

- docs/v6/api/reference/fop/av/avconcat.md
> modify interface content

- docs/v6/api/reference/fop/pfop/pfop.md
> modify response content

- makefile
build method without uploading to qiniu
> add build method to makefile

- docs/v6/api/reference/rs/stat.md
> modify stat interface

- _data/resource.json
- docs/v6/sdk/php-sdk.md
> link 404 bug

- docs/v6/api/reference/fop/av/segtime.md
> modify title

- docs/v6/api/reference/security/put-policy.md
> put-policy add parameter

- docs/v6/api/reference/fop/av/avthumb.md
> 修改avthumb参数

- docs/v6/api/reference/fop/av/avthumb.md
> avthumb接口添加参数

- docs/v6/tools/qfetch.md
- docs/v6/tools/qrsctl.md
- docs/v6/tools/qrsync.md
- docs/v6/tools/qshell.md
添加的工具有：qrsync   qrsctl  qfetch  qshell
> 添加windows用户使用方法

- _data/resource.json
> add resource of F# SDK
